### ISSUE TITLE
Helm chart with redis fails due to 'failed to set key to value'

### ISSUE THREAD

**Issue by mrsheepuk** [banzaicloud/cloudinfo#336]
**Describe the bug**
Installing cloudinfo using the helm chart at 0.7.1 and the default version of the cloudinfo image (0.9.15) fails to create a working environment when enabling redis in the chart, as the scraper cannot write to it, logging errors like the below for every value it tries to write:

`{"application":"cloudinfo","cistore":"redis","environment":"production","key":"/banzaicloud.com/cloudinfo/providers/google/regions/asia-northeast3/prices/n1-highcpu-2","level":"error","msg":"failed to set key to value","time":"2020-06-22T09:21:22Z","value":{"onDemandPrice":0.0909891416015625,"spotPrice":{}}}`

**Steps to reproduce the issue:**
`helm install cloudinftest banzaicloud-stable/cloudinfo -f ./cloudinfo-deploy.yml`

... with the following values in cloudinfo-deploy.yml (including correct and valid google credentials):

```
providers:
  google:
    enabled: true
    credentials: **redacted**
store:
  redis:
    enabled: true

redis:
  enabled: true

  # TODO: support redis password
  usePassword: false
  cluster:
    enabled: false
```

**Expected behavior**
Scraper works as expected and posts values into redis for the application.

**Screenshots**
n/a

**Additional context**
Tested only with Google Cloud enabled at this time.
